ALTER TABLE phrases
  MODIFY COLUMN user_id CHAR(36) NOT NULL AFTER id,
  MODIFY COLUMN content TEXT NOT NULL AFTER user_id,
  MODIFY COLUMN position INT NOT NULL DEFAULT 0 AFTER content,
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER position,
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

DROP TABLE phrases_uuid_backup;
